### ISSUE TITLE
Doku für GitHub Projekt

### ISSUE THREAD

**Issue by dariobro** [whiteducksoftware/azure-devops-build-agent#13]
GitHub Projekt aufhübschen
- Dokumentation
  - Forms im Marketplace
  - Anbindung an DevOps
  - Zugriff über private IP
 - [x] deployment über UI beschreiben
- [x] screenshots einfügen (nach preview publishing)
- [x] container job examples

**Comment by nmeisenzahl** [comment]
@msuemmchen Ist es ausreichend wenn wir die Doku des Build Agents im Repo anlegen und im Marketplace nur darauf verlinken?

**Comment by dariobro** [comment]
@nmeisenzahl Meinst du damit, dass es sich um eine managed application handelt?

**Comment by nmeisenzahl** [comment]
@dariobro We also should include some sample code on how to run container jobs and container build. Below some snippets that could be reused:

``` yaml
pool: my-pool

trigger:
  branches:
    include:
    - master
    - main

variables:
  DOCKER_BUILDKIT: 1

stages:
- stage: build
  jobs:
  - job: build
    displayName: build
    steps:
    - task: Docker@2
      displayName: build
      inputs:
        command: build
        repository: my-image
        tags: $(Build.BuildId)
```

``` yaml
pool: my-pool

trigger:
  branches:
    include:
    - master
    - main

stages:
- stage: build
  jobs:
  - job: build
    displayName: build
    container:
      image: ubuntu:20.04
      # endpoint: 'myServiceConnection'
    steps:
    - task: Bash@3
      displayName: echo
      inputs:
        targetType: 'inline'
        script: echo "hello"
```
